# Generated by Django 5.2.1 on 2025-05-21 11:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artists', '0003_artist_artists_art_first_n_595f32_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.artist')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['title'], name='Hits_hit_title_d16dae_idx'), models.Index(fields=['created_at'], name='Hits_hit_created_18bbf6_idx'), models.Index(fields=['artist'], name='Hits_hit_artist__5bec33_idx')],
            },
        ),
    ]
