# Generated by Django 5.2.1 on 2025-05-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0003_artist_artists_art_first_n_595f32_idx_and_more'),
        ('Hits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit', to='Artists.artist'),
        ),
    ]
