# Generated by Django 5.2.1 on 2025-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_alter_artist_first_name_alter_artist_last_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['first_name'], name='Artists_art_first_n_595f32_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['last_name'], name='Artists_art_last_na_efa940_idx'),
        ),
    ]
